name: circle_translate

on:
  schedule:
    - cron: "0 16 * * 2"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Do translate
        run: |
          python main.py
          ls -al rss/

      - name: Push translated rss
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
        run: |
          pwd
          git config --local user.name "${U_NAME}"
          git config --local user.email "${U_EMAIL}"

          git status -s
          git add .

          export TZ='Asia/Shanghai'
          git commit -m "Github RSS Translate Auto Builder at `date +"%Y-%m-%d %H:%M"`"
          git push
